(define-module (lotus packages ms)
  #:use-module (ice-9 ftw)
  #:use-module (lotus build patchelf-utils)
  #:use-module ((guix licenses) #:prefix license:)
  #:use-module (guix packages)
  #:use-module (guix download)
  #:use-module (guix build rpath)
  #:use-module (guix build-system trivial)
  #:use-module (lotus build-system rpm)
  #:use-module (lotus build rpm-build-system)
  #:use-module (gnu packages)
  #:use-module (gnu packages bootstrap)
  #:use-module (gnu packages base)
  #:use-module (gnu packages nss)
  #:use-module (gnu packages glib)
  #:use-module (gnu packages xorg)
  #:use-module (gnu packages xml)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages gtk)
  #:use-module (gnu packages cups)
  #:use-module (gnu packages gcc)
  #:use-module (gnu packages gnome)
  #:use-module (gnu packages commencement)
  #:use-module (gnu packages gl)
  #:use-module (gnu packages linux)
  #:use-module (gnu packages fontutils)
  #:use-module (gnu packages bash)
  #:use-module (gnu packages chromium))





(define-public rpm-teams
  (package (name "rpm-teams")
           (version "1.3.00.5153-1")
           (source (origin (method    url-fetch)
                           (uri       (string-append "https://packages.microsoft.com/yumrepos/ms-teams/teams-" version ".x86_64.rpm"))
                           (file-name (string-append "teams-" version ".x86_64.rpm"))
                           (sha256    (base32 "009rh55r56k1zd7spiz6hy5chgkq9bg4d0zim9rwjyg28754r4zy"))))
           (inputs `(("chromium"                 ,ungoogled-chromium)
                     ("bash"                     ,bash)
                     ("alsa-lib"                 ,alsa-lib)
                     ("atk"                      ,atk)
                     ("at-spi2-atk"              ,at-spi2-atk)
                     ("cairo"                    ,cairo)
                     ("cups"                     ,cups)
                     ("cups-minimal"             ,cups-minimal)
                     ("dbus"                     ,dbus)
                     ("expat"                    ,expat)
                     ("gcc:lib"                  ,gcc "lib")
                     ("gcc-toolchain"            ,gcc-toolchain)
                     ("gdk-pixbuf"               ,gdk-pixbuf)
                     ("gdk-pixbuf+svg"           ,gdk-pixbuf+svg)
                     ("gfortran:lib"             ,gfortran "lib")
                     ("glib"                     ,glib)
                     ("glibc"                    ,glibc)
                     ("gtk+"                     ,gtk+)
                     ("libgnome-keyring"         ,libgnome-keyring)
                     ("libsecret"                ,libsecret)
                     ("libx11"                   ,libx11)
                     ("libxcb"                   ,libxcb)
                     ("libxcomposite"            ,libxcomposite)
                     ("libxcursor"               ,libxcursor)
                     ("libxdamage"               ,libxdamage)
                     ("libxext"                  ,libxext)
                     ("libxfixes"                ,libxfixes)
                     ("libxi"                    ,libxi)
                     ("libxkbfile"               ,libxkbfile)
                     ("libxrandr"                ,libxrandr)
                     ("libxrender"               ,libxrender)
                     ("libxscrnsaver"            ,libxscrnsaver)
                     ("libxtst"                  ,libxtst)
                     ("mesa"                     ,mesa)
                     ("nspr"                     ,nspr)
                     ("nss"                      ,nss)
                     ("pango"                    ,pango)
                     ("util-linux"               ,util-linux)
                     ("util-linux:lib"           ,util-linux "lib")
                     ("util-linux-with-udev:lib" ,util-linux+udev "lib")
                     ("fontconfig"               ,fontconfig)))
           (native-inputs `(("bash"              ,bash)))
           (build-system rpm-build-system)
           (arguments `(#:input-lib-mapping '(("out" "share/teams")
                                              ("out" "share/teams/swiftshader")
                                              ("nss" "lib/nss"))))
           (synopsis "rpm-teams")
           (description "rpm-teams.")
           (home-page "https://teams")
           (license license:asl2.0)))

rpm-teams
